# Generated by Django 3.1.4 on 2021-01-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('job_location', models.CharField(max_length=100, null=True)),
                ('job_type', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('last_date', models.DateField(null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('company_logo_image', models.FileField(null=True, upload_to='post_job_company_logo/')),
                ('recruiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.recruiter')),
            ],
        ),
    ]
