# Generated by Django 3.1.4 on 2021-01-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_postjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='website_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
