# Generated by Django 3.1.4 on 2021-01-16 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_postjob_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='candidate_resume/')),
                ('candi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.candidate')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.postjob')),
            ],
        ),
    ]
