# Generated by Django 3.1.4 on 2021-01-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_applyjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='candi',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='applyjob',
            old_name='job',
            new_name='job_applied',
        ),
    ]
