# Generated by Django 3.1.4 on 2021-01-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_auto_20210117_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
