# Generated by Django 3.1.4 on 2021-01-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0009_bookmarkjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
