# Generated by Django 3.1.4 on 2021-02-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0010_auto_20210121_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostJob',
            new_name='Job',
        ),
    ]
