# Generated by Django 3.1.4 on 2021-02-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0011_auto_20210202_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
