# Generated by Django 3.1.4 on 2021-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0012_applyjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
