# Generated by Django 3.1.4 on 2021-03-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobportal', '0014_query_queryreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_number', models.BigIntegerField(null=True)),
                ('dob', models.DateField(null=True)),
                ('admin_image', models.FileField(null=True, upload_to='admin_profile/')),
                ('gender', models.CharField(max_length=50, null=True)),
                ('uname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
